dist: focal
language: python

matrix:
    include:
        - python: '2.7'
          dist: bionic
          env:

        - python: '3.7'
          env:

        - python: '3.8'
          env:

        - python: '3.9'
          env:
            - COVERAGE="true"

        - python: '3.10'
          env:

        - python: '3.11-dev'
          env:

        - python: 'pypy2.7-7.3.1' # most recent
          dist: xenial
          env:

        - python: 'pypy3.7-7.3.5' # most recent
          dist: bionic
          env:

    allow_failures:
        - python: '2.7'
        - python: 'pypy2.7-7.3.1'
        - python: '3.11-dev'
    fast_finish: true

cache:
    pip: true

before_install:
    - set -e  # fail on any error
    - if [[ $COVERAGE == "true" ]]; then pip install coverage; fi

install:
    - python -m pip install .

script:
    - for test in examples/*.py; do if [[ $test != *"__"* ]]; then echo $test ; if [[ $COVERAGE == "true" ]]; then coverage run -a $test > /dev/null; else python $test > /dev/null; fi ; fi ; done

after_success:
    - if [[ $COVERAGE == "true" ]]; then bash <(curl -s https://codecov.io/bash); else echo ''; fi
    - if [[ $COVERAGE == "true" ]]; then coverage report; fi
